# Generated by Django 2.2.7 on 2019-12-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_auto_20191204_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza_mascota',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='RazaMascota',
        ),
    ]
