# Generated by Django 3.0 on 2019-12-11 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_auto_20191205_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_medicina', models.CharField(max_length=70)),
                ('descripcion_med', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_vacuna', models.CharField(max_length=70)),
                ('descripcion_vac', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('prediagnostico', models.CharField(blank=True, max_length=150, null=True)),
                ('indicaciones', models.CharField(max_length=250)),
                ('sistema_afectado', models.CharField(blank=True, max_length=100, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_trat_vac', models.CharField(max_length=50)),
                ('nomb_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Vacuna')),
                ('registro_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.RegistroClinico')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMedicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_trat_med', models.CharField(max_length=50)),
                ('nomb_medicina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Medicina')),
                ('registro_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.RegistroClinico')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Complicaciones mínimas', 'Complicaciones mínimas'), ('Crítico', 'Crítico'), ('Fallecido', 'Fallecido')], default='Activo', max_length=22)),
                ('adicional', models.CharField(blank=True, max_length=250, null=True)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Mascota')),
            ],
        ),
    ]
