# Generated by Django 3.0 on 2019-12-11 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_auto_20191211_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmascota',
            name='mascota_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
