# Generated by Django 3.0 on 2019-12-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20191210_1557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasklist',
            unique_together={('name', 'slug')},
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='group',
        ),
    ]
