# Generated by Django 2.2.6 on 2019-10-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nomb', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nomb', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Listo para ser vendido'), ('AGOTADO', 'Producto agotado'), ('REABASTECIENDO', 'Reabastecimiento en proceso')], default='AGOTADO', max_length=20)),
                ('cat_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Categoria')),
            ],
        ),
    ]
