# Generated by Django 3.0 on 2019-12-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Listo para ser vendido'), ('AGOTADO', 'Producto agotado'), ('BAJO STOCK', 'Bajo stock del producto')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Solo número', max_digits=6),
        ),
    ]
