# Generated by Django 2.2.7 on 2019-12-04 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_usr', models.CharField(max_length=200)),
                ('ap_usr', models.CharField(max_length=200)),
                ('tel_usr', models.PositiveIntegerField(blank=True, help_text='Teléfono de contacto', validators=[django.core.validators.MinValueValidator(6)])),
                ('cel_usr', models.IntegerField(help_text='Celular de contacto', validators=[django.core.validators.MinValueValidator(9)])),
                ('dir_usr', models.CharField(max_length=300)),
            ],
        ),
    ]
