# Generated by Django 2.2.7 on 2019-11-23 16:38

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_usr', models.CharField(max_length=200)),
                ('ap_usr', models.CharField(max_length=200)),
                ('tel_usr', phone_field.models.PhoneField(blank=True, help_text='Telefono de contacto', max_length=31)),
                ('cel_usr', phone_field.models.PhoneField(help_text='Celular de contacto', max_length=31)),
                ('dir_usr', models.CharField(max_length=300)),
            ],
        ),
    ]
