# Generated by Django 2.2.7 on 2019-12-04 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tel_usr',
            field=models.PositiveIntegerField(blank=True, help_text='Teléfono de contacto', null=True, validators=[django.core.validators.MinValueValidator(6)]),
        ),
    ]
